# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20180225_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
