# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='logo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
