# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20180226_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
