# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_auto_20180302_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
