# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_remove_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
